name: robot-mujoco-rl
channels:
  - conda-forge
dependencies:
  - python==3.11
  - mujoco-python<3
  - pyside6==6.6.0
  - scipy==1.14.1
  - stable-baselines3==2.3.2
  - gymnasium==0.29.1
  - tensorboard==2.17.1
  - imageio==2.35.1
  - moviepy==1.0.3
  - onnx==1.15.0
  - pip
